// Exact compatibility identifiers; no third-party code or assets.
namespace JoyRescue { public static class TaxonomyRules {
public static readonly CommonTaxonomy.Rule[] All = {
new CommonTaxonomy.Rule("Adamas.HospitalityCasino", "Play_SlotMachine", "Gamble", "Gaming_Cerebral", "Play_SlotMachine", "HC_SlotMachineBlue", "HC_SlotMachineGreen", "HC_SlotMachineRed"),
new CommonTaxonomy.Rule("Arcjc007.Rimball", "Practice_Football", "Gaming_Football", "Gaming_Dexterity", "Practice_Football", "ConcreteFootballPitch", "DustFootballPitch", "GrassFootballPitch", "SandFootballPitch", "WoodFootballPitch"),
new CommonTaxonomy.Rule("Barsimmon.OriginalByVagabond.FantasyGoblins", "Play_TribalDrum", "Gaming_Dexterity", "HighCulture", "Play_TribalDrum", "TribalDrum"),
new CommonTaxonomy.Rule("Basarab.ReligionsOfRimworld", "Pray", "PrayingKind", "Meditative", "PrayToGod", "Altar"),
new CommonTaxonomy.Rule("Bendigeidfran.Rimstation13.Core", "RS13_JoyGiver_ArcadeMachine", "Gaming_Cerebral", "JoyRescue_Kind_taxonomy_video", "RS13_Job_Joy_ArcadeMachine", "RS13_Furniture_Recreation_ArcadeMachine"),
new CommonTaxonomy.Rule("Bendigeidfran.Rimstation13.Core", "RS13_JoyGiver_SlotMachine", "RS13_JoyKind_Gambling", "Gaming_Cerebral", "RS13_Job_Joy_SlotMachine", "RS13_Furniture_Recreation_SlotMachine"),
new CommonTaxonomy.Rule("CP.Military.Furniture", "RedHorse_ListenToGramophoneJG", "Meditative", "Television", "RedHorse_ListenToMusicPlayer", "RedHorse_FalloutRadio", "RedHorse_PortalRadio", "RedHorse_STALKERRadio", "RedHorse_TacticoolRadio"),
new CommonTaxonomy.Rule("CP.Military.Furniture", "RedHorse_PlayAndListenToGramophoneJG", "Meditative", "Television", "RedHorse_PlayAndListenToMusicPlayer", "RedHorse_FalloutRadio", "RedHorse_PortalRadio", "RedHorse_STALKERRadio", "RedHorse_TacticoolRadio"),
new CommonTaxonomy.Rule("CP.Retro.Joy", "PlayRimtendoES", "Gaming_Video", "JoyRescue_Kind_taxonomy_video", "PlayRimtendoES", "RimtendoESConsole"),
new CommonTaxonomy.Rule("CP.Uncle.Boris.Used.Furniture", "RedHorse_ListenToRadio", "Meditative", "HighCulture", "RedHorse_ListenToMusicPlayer", "RH_MusicRadio"),
new CommonTaxonomy.Rule("Caoyuanfei.YuranShrineJapaneseArchitecture", "ReadingBlessingRack", "Social", "Reading", "SocialRelax", "Yuran_BlessingRack"),
new CommonTaxonomy.Rule("D4egon.arcadeworld", "PlayArcadeCabinet_Cerebral", "Gaming_Cerebral", "JoyRescue_Kind_taxonomy_video", "PlayArcadeCabinet_Cerebral", "Arcade_Cabinet"),
new CommonTaxonomy.Rule("D4egon.arcadeworld", "PlayArcadeCabinet_Dexterity", "Gaming_Dexterity", "JoyRescue_Kind_taxonomy_video", "PlayArcadeCabinet_Dexterity", "Arcade_Cabinet"),
new CommonTaxonomy.Rule("D4egon.arcadeworld", "PlayArcadeCabinet_Television", "Television", "JoyRescue_Kind_taxonomy_video", "PlayArcadeCabinet_Television", "Arcade_Cabinet"),
new CommonTaxonomy.Rule("Dajian.ChiTeaditional.Expanded", "JobGiver_DaMaJiang", "Joy_Chi_B", "Gaming_Cerebral", "Job_DaMaJiang", "SZ_MaJiangZhuo"),
new CommonTaxonomy.Rule("Dajian.ChiTeaditional.Expanded", "WatchPekingOpera", "Joy_Chi_A", "Television", "WatchPekingOpera", "Chi_JingJuZhanTai"),
new CommonTaxonomy.Rule("Dajian.ChiTeaditional.Expanded.OldMode", "JobGiver_DaMaJiang", "Joy_Chi_B", "Gaming_Cerebral", "Job_DaMaJiang", "SZ_MaJiangZhuo"),
new CommonTaxonomy.Rule("Dajian.ChiTeaditional.Expanded.OldMode", "WatchPekingOpera", "Joy_Chi_A", "Television", "WatchPekingOpera", "Chi_JingJuZhanTai"),
new CommonTaxonomy.Rule("DankPyon.Medieval.Overhaul", "DankPyon_Play_RimWar", "Gaming_Cerebral", "Gaming_Dexterity", "DankPyon_Play_RimWar", "DankPyon_RimWar"),
new CommonTaxonomy.Rule("Dubwise.DubsBadHygiene", "UseDBHSauna", "Hydrotherapy", "JoyRescue_Kind_taxonomy_wellbeing", "DBHUseSauna", "DBHSaunaHeaterElec", "DBHSaunaHeaterLog"),
new CommonTaxonomy.Rule("Dubwise.DubsBadHygiene", "UseDBHSwimmingPool", "Hydrotherapy", "Gaming_Dexterity", "DBHGoSwimming", "DBHSwimmingPool"),
new CommonTaxonomy.Rule("Dubwise.DubsBadHygiene", "UseHotTub", "Hydrotherapy", "JoyRescue_Kind_taxonomy_wellbeing", "UseHotTub", "HotTub"),
new CommonTaxonomy.Rule("DuelMonster.RimWorld", "Play_GameOfDMRW", "Gaming_Cerebral", "Television", "Play_GameOfDMRW", "DuelTerminal"),
new CommonTaxonomy.Rule("Floor.Mounted.Aquarium", "FishWatching", "FishWatching", "Meditative", "WatchFish", "FMAquariumL", "FMAquariumSm", "FMAquariumT"),
new CommonTaxonomy.Rule("Fox.SimpleLearning", "Fox_Book_read", "Meditative", "Reading", "Fox_Read_Joy", "Library_Table"),
new CommonTaxonomy.Rule("Fox.SimpleLearning", "Fox_Book_read_Animals", "Meditative", "Reading", "Fox_Read_Animals", "Library_Table"),
new CommonTaxonomy.Rule("Fox.SimpleLearning", "Fox_Book_read_Art", "Meditative", "Reading", "Fox_Read_Art", "Library_Table"),
new CommonTaxonomy.Rule("Fox.SimpleLearning", "Fox_Book_read_Construct", "Meditative", "Reading", "Fox_Read_Construct", "Library_Table"),
new CommonTaxonomy.Rule("Fox.SimpleLearning", "Fox_Book_read_Cooking", "Meditative", "Reading", "Fox_Read_Cooking", "Library_Table"),
new CommonTaxonomy.Rule("Fox.SimpleLearning", "Fox_Book_read_Crafting", "Meditative", "Reading", "Fox_Read_Crafting", "Library_Table"),
new CommonTaxonomy.Rule("Fox.SimpleLearning", "Fox_Book_read_Intellectual", "Meditative", "Reading", "Fox_Read_Intellectual", "Library_Table"),
new CommonTaxonomy.Rule("Fox.SimpleLearning", "Fox_Book_read_Medical", "Meditative", "Reading", "Fox_Read_Medical", "Library_Table"),
new CommonTaxonomy.Rule("Fox.SimpleLearning", "Fox_Book_read_Melee", "Meditative", "Reading", "Fox_Read_Melee", "Library_Table"),
new CommonTaxonomy.Rule("Fox.SimpleLearning", "Fox_Book_read_Mining", "Meditative", "Reading", "Fox_Read_Mining", "Library_Table"),
new CommonTaxonomy.Rule("Fox.SimpleLearning", "Fox_Book_read_Plants", "Meditative", "Reading", "Fox_Read_Plants", "Library_Table"),
new CommonTaxonomy.Rule("Fox.SimpleLearning", "Fox_Book_read_Shoot", "Meditative", "Reading", "Fox_Read_Shoot", "Library_Table"),
new CommonTaxonomy.Rule("Fox.SimpleLearning", "Fox_Read_Social", "Meditative", "Reading", "Fox_Read_Social", "Library_Table"),
new CommonTaxonomy.Rule("Fox.SimpleLearning", "Fox_Shoot_Book_Skim", "Meditative", "Gaming_Dexterity", "Fox_Skim_Shoot", "Shooting_Bookshelf"),
new CommonTaxonomy.Rule("Gloomy.Furniture.Continued", "JoyGiver_ListenSong", "JoyKind_ListenSong", "HighCulture", "JobDef_ListenSong", "JukeBox"),
new CommonTaxonomy.Rule("Gloomy.Furniture.Continued.Fix", "JoyGiver_ListenSong", "JoyKind_ListenSong", "HighCulture", "JobDef_ListenSong", "JukeBox"),
new CommonTaxonomy.Rule("Gloomy.Furniture.Fix", "JoyGiver_ListenSong", "JoyKind_ListenSong", "HighCulture", "JobDef_ListenSong", "JukeBox"),
new CommonTaxonomy.Rule("Grok.GamersRig", "GR_PlayComputer", "GR_JoyVideoGames", "JoyRescue_Kind_taxonomy_video", "GR_PlayComputer", "GR_GamingComputer"),
new CommonTaxonomy.Rule("HRG164hjo.PerfectlyGenericItem.Overpower", "PGI_SoS_ShipWatch", "Telescope", "Reading", "UseTelescope", "PGI_SoS_ShipLookhole", "PGI_SoS_ShipLookholeAuto"),
new CommonTaxonomy.Rule("Haplo.Miscellaneous.TrainingNoTask", "PracticeMartialArts", "Gaming_MartialArts", "Gaming_Dexterity", "UseMartialArtsTarget", "MartialArtsTarget"),
new CommonTaxonomy.Rule("Haplo.Miscellaneous.TrainingNoTask", "PracticeShooting", "Gaming_Shooting", "Gaming_Dexterity", "UseShootingRange", "ShootingRangeTarget"),
new CommonTaxonomy.Rule("Haplo.Miscellaneous.TrainingNoTask", "ShootSomeArrows", "Gaming_Shooting", "Gaming_Dexterity", "ArcheryShootArrows", "ArcheryTarget"),
new CommonTaxonomy.Rule("Heis.Edo.Themed.Expansion", "HSPlay_Haikuspot", "HSMade_Haiku", "JoyRescue_Kind_taxonomy_creative", "HSPlay_Haikuspot", "HS_HaikuSpot"),
new CommonTaxonomy.Rule("KindSeal.UFLI", "UFLI_UseBenchrack", "UFLI_Gym", "Gaming_Dexterity", "UFLI_UseBenchrack", "UFLI_Benchrack"),
new CommonTaxonomy.Rule("KindSeal.UFLI", "UFLI_UseDumbbellrack", "UFLI_Gym", "Gaming_Dexterity", "UFLI_UseDumbbellrack", "UFLI_Dumbbellrack"),
new CommonTaxonomy.Rule("KindSeal.UFLI", "UFLI_UseGymbike", "UFLI_Gym", "Gaming_Dexterity", "UFLI_UseGymbike", "UFLI_Gymbike"),
new CommonTaxonomy.Rule("KindSeal.UFLI", "UFLI_UseTelescope", "Telescope", "Reading", "UFLI_UseTelescope", "UFLI_Telescope"),
new CommonTaxonomy.Rule("KindSeal.UFLI", "UFLI_UseTreadmill", "UFLI_Gym", "Gaming_Dexterity", "UFLI_UseTreadmill", "UFLI_Treadmill"),
new CommonTaxonomy.Rule("Kyzy.bioranch", "BioRanchVisit", "BioRanchAnimalViewing", "Meditative", "BioRanchVisit", "BioRanch", "BioRanchHuge", "SimpleRanch"),
new CommonTaxonomy.Rule("Kyzy.potokenfield", "WatchPotokenField", "PotokenObservation", "Meditative", "WatchPotokenField", "PotokenField"),
new CommonTaxonomy.Rule("Ludeon.RimWorld", "UseTelescope", "Telescope", "Reading", "UseTelescope", "Telescope"),
new CommonTaxonomy.Rule("Mdtk.Compboards", "MD_PlayCR", "PlayCR", "JoyRescue_Kind_taxonomy_video", "PlayCompboard", "MD_ACCR", "MD_ACR", "MD_BCR", "MD_CCR", "MD_GCR"),
new CommonTaxonomy.Rule("Mlie.CallofCthulhuIndustrialAge", "Estate_ListenToGramophoneJG", "Meditative", "Television", "ListenToGramophone", "Estate_Gramophone", "Estate_Radio"),
new CommonTaxonomy.Rule("Mlie.CallofCthulhuIndustrialAge", "Estate_PlayAndListenToGramophoneJG", "Meditative", "Television", "PlayAndListenToGramophone", "Estate_Gramophone", "Estate_Radio"),
new CommonTaxonomy.Rule("Mlie.JurassicRimworld", "UseViewingDome", "ViewingDome", "Meditative", "UseViewingDome", "ViewingDomeEntrance"),
new CommonTaxonomy.Rule("Mlie.MMDrumcanMOD", "Joy_BathingAtDrumBath", "JoyKind_BathingAtDrumBath", "JoyRescue_Kind_taxonomy_wellbeing", "Job_BathingAtDrumBath", "DrumBath"),
new CommonTaxonomy.Rule("Mlie.MMDrumcanMOD", "Pushing_a_drumcan", "Push_the_drumcan", "Gaming_Dexterity", "Pushing_a_drumcan", "PushingDrumcan"),
new CommonTaxonomy.Rule("Mlie.MusicalInstruments", "MusicListen", "Music", "HighCulture", "MusicListen", "ElectronicOrgan", "FrameDrum", "Guitar", "Ocarina", "Violin"),
new CommonTaxonomy.Rule("Mlie.MusicalInstruments", "MusicPlay", "Music", "HighCulture", "MusicPlayJoy", "ElectronicOrgan", "FrameDrum", "Guitar", "Ocarina", "Violin"),
new CommonTaxonomy.Rule("Mlie.NewJoySourcePlayMusic", "PlayPiano", "Social", "HighCulture", "PlayPiano", "M4_SPiano"),
new CommonTaxonomy.Rule("Mlie.RimWriter", "RimWriter_AutoWriteJG", "Jecrell_Writing", "JoyRescue_Kind_taxonomy_creative", "RimWriter_AutoWrite", "RimWriter_TableTypewriter", "RimWriter_TableWriting"),
new CommonTaxonomy.Rule("Mlie.RimWriter", "RimWriter_FreeWriteJG", "Jecrell_Writing", "JoyRescue_Kind_taxonomy_creative", "RimWriter_FreeWrite", "RimWriter_TableTypewriter", "RimWriter_TableWriting"),
new CommonTaxonomy.Rule("Mlie.RimWriter", "RimWriter_ReadABookJG", "Jecrell_Writing", "Reading", "RimWriter_ReadABook", "Jecrell_Bookcase"),
new CommonTaxonomy.Rule("Mlie.VanillaBooksExpandedExpanded", "VanillaBooksExpandedExpanded_ReadIdeoBook", "VBE_Reading", "Reading", "VanillaBooksExpandedExpanded_ReadIdeoBook", "VanillaBooksExpandedExpanded_IdeoligionBook"),
new CommonTaxonomy.Rule("Neronix17.OuterRim.Core", "OuterRim_ResearchJoy", "Gaming_Cerebral", "Reading", "OuterRim_ResearchJoyJob", "OuterRim_HypertechTerminal", "OuterRim_HypertechTerminalWide"),
new CommonTaxonomy.Rule("Neronix17.OuterRim.FurnitureAndDecor", "OuterRim_HoloNetArcades", "OuterRim_HoloNetArcade", "JoyRescue_Kind_taxonomy_video", "OuterRim_HoloNetArcadePlay", "OuterRim_HoloArcade_MynockHunt"),
new CommonTaxonomy.Rule("OARK.RatkinKnightOrderFurniture", "OARO_PlayCarrierPigeon", "OARO_CarrierPigeon", "Social", "OARO_PlayCarrierPigeon", "OARO_OrderLetterBox"),
new CommonTaxonomy.Rule("OARK.RatkinKnightOrderFurniture", "OARO_SandboxExercise", "Gaming_Cerebral", "Gaming_Dexterity", "OARO_SandboxExercise", "OARO_InferentialSandTable"),
new CommonTaxonomy.Rule("OskarPotocki.VFE.Classical", "VFEC_Relax_Thermaebath", "VFEC_Relaxing_Bath", "JoyRescue_Kind_taxonomy_wellbeing", "VFEC_Relax_Thermaebath", "VFEC_Thermaebath"),
new CommonTaxonomy.Rule("Paintable.Gloomy.Furniture", "JoyGiver_ListenSong", "JoyKind_ListenSong", "HighCulture", "JobDef_ListenSong", "JukeBox"),
new CommonTaxonomy.Rule("Para0234.SNSAmbitionCosmic", "Use_SNS_Telescope_GenI", "Telescope", "Reading", "Use_SNS_Telescope_GenI", "SNS_Telescope_GenI"),
new CommonTaxonomy.Rule("Para0234.SNSAmbitionCosmic", "Use_SNS_Telescope_GenII", "Telescope", "Reading", "Use_SNS_Telescope_GenII", "SNS_Telescope_GenII"),
new CommonTaxonomy.Rule("Para0234.SNSAmbitionCosmic", "Use_SNS_Telescope_GenIII", "Telescope", "Reading", "Use_SNS_Telescope_GenIII", "SNS_Telescope_GenIII"),
new CommonTaxonomy.Rule("RI.RimImmortals.SeasonsOfRule", "XXK_RI_WuShuPractice", "XXK_RI_WuShuPractice", "Gaming_Dexterity", "XXK_RI_WuShuPractice", "XXK_RI_WuShuPractice_Pillar"),
new CommonTaxonomy.Rule("Resurrectionem.Furniture", "RRPlay_ComputerLow", "RRGaming_Electronic", "JoyRescue_Kind_taxonomy_video", "RRPlay_ComputerLow", "RRDesktop", "RRDesktopThree", "RRDesktopTwo"),
new CommonTaxonomy.Rule("Resurrectionem.Furniture", "RRPlay_MusicListening", "RRMusicListening", "HighCulture", "RRPlay_MusicListening", "RRBigStereoConsole", "RRGojaRadio", "RRStereoConsole"),
new CommonTaxonomy.Rule("Roo.AntyRaceMod", "AT_ChartCheck", "AT_ChartCheck", "Reading", "AT_ChartCheck", "AT_Chart"),
new CommonTaxonomy.Rule("Salvador143.MThings.Medical", "MThingsWatchShadowbox", "MThingsContemplation", "Meditative", "MThingsWatchShadowbox", "MThingsExpandedShadowbox", "MThingsShadowbox"),
new CommonTaxonomy.Rule("Solaris.FurnitureBase", "JoyGiver_ListenSong", "JoyKind_ListenSong", "HighCulture", "JobDef_ListenSong", "JukeBox"),
new CommonTaxonomy.Rule("Takumunt.RimGamble", "PlayGachaMachine", "Gambling", "Gaming_Cerebral", "RimGamble_PlayGachaMachine", "RimGamble_GachaMachine"),
new CommonTaxonomy.Rule("Takumunt.RimGamble", "PlaySlotMachine", "Gambling", "Gaming_Cerebral", "RimGamble_PlaySlotMachine", "RimGamble_SlotMachine"),
new CommonTaxonomy.Rule("Thekiborg.HOTL", "HOTL_JoyGiver_Massage", "HOTL_JoyKind_Massage", "JoyRescue_Kind_taxonomy_wellbeing", "HOTL_BottomMassage", "HOTL_MassageBed"),
new CommonTaxonomy.Rule("Trickity.Samurai.Faction", "Play_CalligraphySet", "Did_Art", "JoyRescue_Kind_taxonomy_creative", "Play_CalligraphySet", "TSF_CalligraphySet"),
new CommonTaxonomy.Rule("Udon.Ricecultivatingcivilization.for14", "Play_BozuMekuri", "Enjoy_WA", "Gaming_Cerebral", "Play_BozuMekuri", "WA_Karuta"),
new CommonTaxonomy.Rule("Udon.Ricecultivatingcivilization.for14", "Play_PoemCardGame", "Enjoy_WA", "Gaming_Cerebral", "Play_PoemCardGame", "WA_Karuta"),
new CommonTaxonomy.Rule("Udon.Ricecultivatingcivilization.for14", "Play_ShellMatching", "Enjoy_WA", "Gaming_Cerebral", "Play_ShellMatching", "WA_ShellMatching"),
new CommonTaxonomy.Rule("Udon.Ricecultivatingcivilization.for14", "Play_Sugoroku", "Social", "Gaming_Cerebral", "Play_Sugoroku", "WA_Sugoroku"),
new CommonTaxonomy.Rule("Valensia.Palim", "Palim_PlayOrgel", "Gaming_Dexterity", "HighCulture", "Palim_PlayOrgel", "Palim_Orgel"),
new CommonTaxonomy.Rule("VanillaExpanded.VFECore", "Play_Arcade", "Gaming_Cerebral", "JoyRescue_Kind_taxonomy_video", "Play_Arcade", "Joy_Arcade"),
new CommonTaxonomy.Rule("VanillaExpanded.VFECore", "Play_ComputerIndustrial", "Gaming_Electronic", "JoyRescue_Kind_taxonomy_video", "Play_ComputerIndustrial", "Joy_InudstrialComputer"),
new CommonTaxonomy.Rule("VanillaExpanded.VFECore", "Play_ComputerModern", "Gaming_Electronic", "JoyRescue_Kind_taxonomy_video", "Play_ComputerModern", "Joy_ModernComputer"),
new CommonTaxonomy.Rule("VanillaExpanded.VFECore", "Play_PunchingBag", "VFE_StrengthPlay", "Gaming_Dexterity", "Play_PunchingBag", "Joy_PunchingBag"),
new CommonTaxonomy.Rule("VanillaExpanded.VFECore", "VFE_Play_Sunbathing", "Meditative", "JoyRescue_Kind_taxonomy_wellbeing", "VFE_Play_Sunbathing", "VFE_Lounger"),
new CommonTaxonomy.Rule("Verniy709.Annelitrice2.0", "WatchPuppetShow", "Annely_Spectate", "Television", "WatchPuppetShow", "Anneli_PuppetTheatre"),
new CommonTaxonomy.Rule("Verniy709.Annelitrice3.0", "WatchPuppetShow", "Anneli_Spectate", "Television", "WatchPuppetShow", "Anneli_PuppetTheatre"),
new CommonTaxonomy.Rule("Xeva.HSRetexture.11", "StandaloneHotSpringEX", "Meditative", "JoyRescue_Kind_taxonomy_wellbeing", "BathStandaloneHotSpring", "StandaloneHotSpringEXE", "StandaloneHotSpringEXJ"),
new CommonTaxonomy.Rule("ZuoYao.RavenRace", "Raven_JoyGiver_TakeSlimeBath", "Raven_SlimeBathJoy", "JoyRescue_Kind_taxonomy_wellbeing", "Raven_Job_TakeSlimeBath", "Raven_Building_SlimeBathtub"),
new CommonTaxonomy.Rule("apitec.plus", "ApiPlus_WatchLightshow", "ApiPlus_Lightshow", "Television", "ApiPlus_WatchLights", "ApiPlus_PrismaticHoloimager"),
new CommonTaxonomy.Rule("balistafreak.StandaloneHotSpring", "BathStandaloneHotSpring", "Meditative", "JoyRescue_Kind_taxonomy_wellbeing", "BathStandaloneHotSpring", "StandaloneHotSpring"),
new CommonTaxonomy.Rule("ben.ajolite", "AJO_InterpretArt", "AJO_Study", "Reading", "AJO_InterpretArt", "AJO_Painting"),
new CommonTaxonomy.Rule("ben.ajolite", "AJO_PlayArcadeBG", "Gaming_Cerebral", "JoyRescue_Kind_taxonomy_video", "AJO_PlayArcadeBG", "AJO_ArcadeBG"),
new CommonTaxonomy.Rule("ben.ajolite", "AJO_PlayArcadeCB", "Gaming_Cerebral", "JoyRescue_Kind_taxonomy_video", "AJO_PlayArcadeCB", "AJO_ArcadeCB"),
new CommonTaxonomy.Rule("ben.ajolite", "AJO_PlayArcadeES", "Gaming_Dexterity", "JoyRescue_Kind_taxonomy_video", "AJO_PlayArcadeES", "AJO_ArcadeES"),
new CommonTaxonomy.Rule("ben.ajolite", "AJO_PlayArcadeGD", "AJO_Passive", "JoyRescue_Kind_taxonomy_video", "AJO_PlayArcadeGD", "AJO_ArcadeGD"),
new CommonTaxonomy.Rule("ben.ajolite", "AJO_PlayArcadeHL", "Gaming_Dexterity", "JoyRescue_Kind_taxonomy_video", "AJO_PlayArcadeHL", "AJO_ArcadeHL"),
new CommonTaxonomy.Rule("ben.ajolite", "AJO_PlayArcadeHomebrew", "AJO_Passive", "JoyRescue_Kind_taxonomy_video", "AJO_PlayArcadeHomebrew", "AJO_ArcadeHomebrew"),
new CommonTaxonomy.Rule("ben.ajolite", "AJO_PlayArcadeMC", "Gaming_Dexterity", "JoyRescue_Kind_taxonomy_video", "AJO_PlayArcadeMC", "AJO_ArcadeMC"),
new CommonTaxonomy.Rule("ben.ajolite", "AJO_PlayArcadePK", "Gaming_Dexterity", "JoyRescue_Kind_taxonomy_video", "AJO_PlayArcadePK", "AJO_ArcadePK"),
new CommonTaxonomy.Rule("ben.ajolite", "AJO_PlayArcadePS", "Gaming_Cerebral", "JoyRescue_Kind_taxonomy_video", "AJO_PlayArcadePS", "AJO_ArcadePS"),
new CommonTaxonomy.Rule("ben.ajolite", "AJO_PlayArcadeRS", "Gaming_Cerebral", "JoyRescue_Kind_taxonomy_video", "AJO_PlayArcadeRS", "AJO_ArcadeRS"),
new CommonTaxonomy.Rule("ben.ajolite", "AJO_PlayArcadeSP", "Gaming_Dexterity", "JoyRescue_Kind_taxonomy_video", "AJO_PlayArcadeSP", "AJO_ArcadeSP"),
new CommonTaxonomy.Rule("ben.ajolite", "AJO_PlayArcadeTV", "Gaming_Dexterity", "JoyRescue_Kind_taxonomy_video", "AJO_PlayArcadeTV", "AJO_ArcadeTV"),
new CommonTaxonomy.Rule("ben.ajolite", "AJO_PlayArcadeTZ", "Social", "JoyRescue_Kind_taxonomy_video", "AJO_PlayArcadeTZ", "AJO_ArcadeTZ"),
new CommonTaxonomy.Rule("ben.ajolite", "AJO_PlayRimColony", "AJO_Gaming_Social", "Social", "AJO_PlayRimColony", "AJO_RimColony"),
new CommonTaxonomy.Rule("daylight.RimLifeExFurMod", "PlayingRLESnooker", "Gaming_RLESnookerTable", "Gaming_Dexterity", "Gaming_RLESnooker", "RLESnookerTable"),
new CommonTaxonomy.Rule("daylight.RimLifeExFurMod", "PlayingRLEWaitingGame", "Gaming_RLEWaitingGame", "Gaming_Cerebral", "Play_RLEWaitingGame", "RLE_WaitingGame"),
new CommonTaxonomy.Rule("daylight.RimLifeExFurMod", "PlayingRP_TabletalkRPG", "Gaming_RLETableTalkRPG", "Gaming_Cerebral", "Play_TabletalkRPG", "RLE_TabletalkRPGTable"),
new CommonTaxonomy.Rule("daylight.RimLifeExFurMod", "Playingmahjong", "PlayMahjongGame", "Gaming_Cerebral", "PlayGameAtmahjongTable", "RLAutomatic_MahjongTable"),
new CommonTaxonomy.Rule("daylight.RimLifeExFurMod", "testOfLuck_BlackJack", "Gaming_BlackJack", "Gaming_Cerebral", "Play_BlackJack", "RLBlackJack_PlayingTable"),
new CommonTaxonomy.Rule("dfifd.joyfulresearch", "Examine_Scientific_Papers", "Scientific_Study", "Reading", "Examine_Scientific_Papers", "HiTechResearchBench", "SimpleResearchBench"),
new CommonTaxonomy.Rule("dninemfive.ajo.paintings", "AJO_InterpretArt", "AJO_Study", "Reading", "AJO_InterpretArt", "AJO_Painting"),
new CommonTaxonomy.Rule("dracoix.ljo.arcades", "LJO_PlayArcadeBG", "Gaming_Cerebral", "JoyRescue_Kind_taxonomy_video", "LJO_PlayArcadeBG", "LJO_ArcadeBG"),
new CommonTaxonomy.Rule("dracoix.ljo.arcades", "LJO_PlayArcadeCB", "Gaming_Cerebral", "JoyRescue_Kind_taxonomy_video", "LJO_PlayArcadeCB", "LJO_ArcadeCB"),
new CommonTaxonomy.Rule("dracoix.ljo.arcades", "LJO_PlayArcadeES", "Gaming_Dexterity", "JoyRescue_Kind_taxonomy_video", "LJO_PlayArcadeES", "LJO_ArcadeES"),
new CommonTaxonomy.Rule("dracoix.ljo.arcades", "LJO_PlayArcadeHomebrew", "Meditative", "JoyRescue_Kind_taxonomy_video", "LJO_PlayArcadeHomebrew", "LJO_ArcadeHomebrew"),
new CommonTaxonomy.Rule("dracoix.ljo.arcades", "LJO_PlayArcadeMC", "Gaming_Cerebral", "JoyRescue_Kind_taxonomy_video", "LJO_PlayArcadeMC", "LJO_ArcadeMC"),
new CommonTaxonomy.Rule("dracoix.ljo.arcades", "LJO_PlayArcadePK", "Gaming_Cerebral", "JoyRescue_Kind_taxonomy_video", "LJO_PlayArcadePK", "LJO_ArcadePK"),
new CommonTaxonomy.Rule("dracoix.ljo.arcades", "LJO_PlayArcadePS", "Gaming_Dexterity", "JoyRescue_Kind_taxonomy_video", "LJO_PlayArcadePS", "LJO_ArcadePS"),
new CommonTaxonomy.Rule("dracoix.ljo.arcades", "LJO_PlayArcadeRS", "Gaming_Cerebral", "JoyRescue_Kind_taxonomy_video", "LJO_PlayArcadeRS", "LJO_ArcadeRS"),
new CommonTaxonomy.Rule("dracoix.ljo.arcades", "LJO_PlayArcadeSP", "Gaming_Dexterity", "JoyRescue_Kind_taxonomy_video", "LJO_PlayArcadeSP", "LJO_ArcadeSP"),
new CommonTaxonomy.Rule("dracoix.ljo.arcades", "LJO_PlayArcadeTV", "Gaming_Dexterity", "JoyRescue_Kind_taxonomy_video", "LJO_PlayArcadeTV", "LJO_ArcadeTV"),
new CommonTaxonomy.Rule("dracoix.ljo.arcades", "LJO_PlayArcadeTZ", "Social", "JoyRescue_Kind_taxonomy_video", "LJO_PlayArcadeTZ", "LJO_ArcadeTZ"),
new CommonTaxonomy.Rule("elkyelky.Rimception", "Play_Computer", "Computer_Gaming", "JoyRescue_Kind_taxonomy_video", "Play_Computer", "GamingDesktop"),
new CommonTaxonomy.Rule("ellit.Rebels", "Plan_Resistance", "Planning_Resistance", "Gaming_Dexterity", "Plan_Resistance", "StrategyTable"),
new CommonTaxonomy.Rule("ellit.Rebels", "Train_Melee", "TrainingCombat", "Gaming_Dexterity", "Train_Melee", "MeleeDummy"),
new CommonTaxonomy.Rule("ellit.Rebels", "Train_Ranged", "TrainingCombat", "Gaming_Dexterity", "Train_Ranged", "RangedDummy"),
new CommonTaxonomy.Rule("explodoboy.AmbitionOfTheCosmic.TempOverhaul", "AOTC_GamingAnimals_GenI", "AOTC_GamingAnimals", "Social", "AOTC_GamingAnimals_GenI", "AOTC_GamingAnimals_GenI"),
new CommonTaxonomy.Rule("explodoboy.AmbitionOfTheCosmic.TempOverhaul", "AOTC_GamingArtistic_GenI", "AOTC_GamingArtistic", "JoyRescue_Kind_taxonomy_creative", "AOTC_GamingArtistic_GenI", "AOTC_GamingArtistic_GenI"),
new CommonTaxonomy.Rule("explodoboy.AmbitionOfTheCosmic.TempOverhaul", "AOTC_GamingConstruction_GenI", "AOTC_GamingConstruction", "JoyRescue_Kind_taxonomy_creative", "AOTC_GamingConstruction_GenI", "AOTC_GamingConstruction_GenI"),
new CommonTaxonomy.Rule("explodoboy.AmbitionOfTheCosmic.TempOverhaul", "AOTC_GamingCooking_GenI", "AOTC_GamingCooking", "JoyRescue_Kind_taxonomy_creative", "AOTC_GamingCooking_GenI", "AOTC_GamingCooking_GenI"),
new CommonTaxonomy.Rule("explodoboy.AmbitionOfTheCosmic.TempOverhaul", "AOTC_GamingCrafting_GenI", "AOTC_GamingCrafting", "JoyRescue_Kind_taxonomy_creative", "AOTC_GamingCrafting_GenI", "AOTC_GamingCrafting_GenI"),
new CommonTaxonomy.Rule("explodoboy.AmbitionOfTheCosmic.TempOverhaul", "AOTC_GamingMelee_GenI", "AOTC_GamingMelee", "Gaming_Dexterity", "AOTC_GamingMelee_GenI", "AOTC_GamingMelee_GenI"),
new CommonTaxonomy.Rule("explodoboy.AmbitionOfTheCosmic.TempOverhaul", "AOTC_GamingPlants_GenI", "AOTC_GamingPlants", "JoyRescue_Kind_taxonomy_creative", "AOTC_GamingPlants_GenI", "AOTC_GamingPlants_GenI"),
new CommonTaxonomy.Rule("explodoboy.AmbitionOfTheCosmic.TempOverhaul", "AOTC_GamingSocial_GenI", "AOTC_GamingSocial", "Social", "AOTC_GamingSocial_GenI", "AOTC_GamingSocial_GenI"),
new CommonTaxonomy.Rule("explodoboy.AmbitionOfTheCosmic.TempOverhaul", "AOTC_GamingTelescope_GenI", "Telescope", "Reading", "AOTC_GamingTelescope_GenI", "AOTC_GamingTelescope_GenI"),
new CommonTaxonomy.Rule("explodoboy.SNSAmbitionCosmic", "Use_SNS_Telescope_GenI", "Telescope", "Reading", "Use_SNS_Telescope_GenI", "SNS_Telescope_GenI"),
new CommonTaxonomy.Rule("explodoboy.SNSAmbitionCosmic", "Use_SNS_Telescope_GenII", "Telescope", "Reading", "Use_SNS_Telescope_GenII", "SNS_Telescope_GenII"),
new CommonTaxonomy.Rule("explodoboy.SNSAmbitionCosmic", "Use_SNS_Telescope_GenIII", "Telescope", "Reading", "Use_SNS_Telescope_GenIII", "SNS_Telescope_GenIII"),
new CommonTaxonomy.Rule("fxz.myafufu", "Play_Fufu", "Playing_Fufu", "Social", "Play_Fufu", "GD_AOBAFufu", "GD_AncotFufu", "GD_AntyFufu", "GD_ApocritonFufu", "GD_AzaleaFufu", "GD_BillFufu", "GD_BunFufu", "GD_DPanielFufu", "GD_DragonianFufu", "GD_EponaFufu", "GD_FengxinziFufu", "GD_HibiscusFufu", "GD_JiuFufu", "GD_KVFufu", "GD_KiiroFufu", "GD_MaruFufu", "GD_MihoFufu", "GD_MiliraFufu", "GD_MinchoFufu", "GD_MirFufu", "GD_MomokaFufu", "GD_MonochaFufu", "GD_MoyoFufu", "GD_MoyuguFufu", "GD_MyaFufu", "GD_NeutronFufu", "GD_PanielFufu", "GD_QiuciFufu", "GD_RabbieJackFufu", "GD_RabbieNicoFufu", "GD_SnowFufu", "GD_VivianFufu", "GD_YuranFufu"),
new CommonTaxonomy.Rule("io.github.cvrunmin.TurretForFun", "TurretFun_WaterPlaying", "TurretFun_Gaming_Water", "Gaming_Dexterity", "TurretFun_WaterPlaying", "TurretFun_WaterCannon"),
new CommonTaxonomy.Rule("kaitorisenkou.BallGames", "Play_Basketball", "Gaming_Agility", "Gaming_Dexterity", "Job_Basketball", "BasketballGoal"),
new CommonTaxonomy.Rule("kaitorisenkou.BallGames", "Play_Soccer", "Gaming_Agility", "Gaming_Dexterity", "Job_Soccer", "SoccerGoal"),
new CommonTaxonomy.Rule("kaitorisenkou.BallGames", "Play_Volleyball", "Gaming_Agility", "Gaming_Dexterity", "Job_Volleyball", "VolleyballNet"),
new CommonTaxonomy.Rule("kdm.lanternhunters", "Play_AugrySpot", "Telescope", "Reading", "Play_AugrySpot", "AugrySpot"),
new CommonTaxonomy.Rule("kdm.lanternhunters", "UseTelescope", "Telescope", "Reading", "UseTelescope", "Telescope"),
new CommonTaxonomy.Rule("kentington.saveourship2", "UseHolodeck", "Holodeck", "JoyRescue_Kind_taxonomy_video", "UseHolodeck", "Holodeck_AI", "Holodeck_Basic", "Holodeck_Standard"),
new CommonTaxonomy.Rule("kentington.saveourship2", "UseTelescopeSpace", "Telescope", "Reading", "UseTelescope", "TelescopeSpace"),
new CommonTaxonomy.Rule("kones.getrimped", "DoTrainingMelee", "Gaming_WorkingOut", "Gaming_Dexterity", "UseGymEquipmentMelee", "BalanceBeam", "Barbell", "Dumbbells", "ExerciseBike", "HandGrip", "JumpRope", "Kettlebell", "PullupBars", "Rack", "Treadmill", "WeightBench", "YogaBall"),
new CommonTaxonomy.Rule("kones.getrimped", "PracticeMartialArts", "Gaming_WorkingOut", "Gaming_Dexterity", "UseMartialArtsTarget", "BalanceBeam", "Barbell", "Dumbbells", "ExerciseBike", "HandGrip", "JumpRope", "Kettlebell", "PullupBars", "Rack", "Treadmill", "WeightBench", "YogaBall"),
new CommonTaxonomy.Rule("meat.TheZoneGuitar", "Play_Guitar", "Social", "HighCulture", "Play_Guitar", "Guitar"),
new CommonTaxonomy.Rule("mlmlmlm.bluearchivejoybojects", "Play_Arcade_Machine", "Gaming_arcade", "JoyRescue_Kind_taxonomy_video", "Play_Arcade_Machine", "Blue_Arcade_Machine", "Purple_Arcade_Machine", "Red_Arcade_Machine"),
new CommonTaxonomy.Rule("mlmlmlm.bluearchivejoybojects", "Play_Jellies_Plush_Claw_Machine", "Gaming_arcade", "JoyRescue_Kind_taxonomy_video", "Play_Jellies_Plush_Claw_Machine", "Jellies_Plush_Claw_Machine"),
new CommonTaxonomy.Rule("nelim.animasong", "AnimaSong_Listen", "AnimaSong_Song", "HighCulture", "AnimaSong_Listen", "Plant_TreeAnima"),
new CommonTaxonomy.Rule("nelim.crystalball", "CB_GazeIntoCrystalBall", "CB_Divination", "Meditative", "CB_GazeIntoCrystalBall", "CB_CrystalBall"),
new CommonTaxonomy.Rule("nelim.entitygazing", "EG_WatchEntity", "EG_EntityGazing", "Meditative", "EG_WatchEntity", "HoldingPlatform", "HoldingSpot"),
new CommonTaxonomy.Rule("nelim.joypreservation", "JP_EnjoyAroma", "JP_EnjoyWa", "JoyRescue_Kind_taxonomy_wellbeing", "JP_EnjoyAroma", "JP_IncenseBurner"),
new CommonTaxonomy.Rule("nelim.joypreservation", "JP_PlayBozuMekuri", "JP_EnjoyWa", "Gaming_Cerebral", "JP_PlayBozuMekuri", "JP_Karuta"),
new CommonTaxonomy.Rule("nelim.joypreservation", "JP_PlayPoemCards", "JP_EnjoyWa", "Gaming_Cerebral", "JP_PlayPoemCards", "JP_Karuta"),
new CommonTaxonomy.Rule("nelim.joypreservation", "JP_PlayShellMatching", "JP_EnjoyWa", "Gaming_Cerebral", "JP_PlayShellMatching", "JP_ShellMatching"),
new CommonTaxonomy.Rule("nelim.joypreservation", "JP_PlaySugoroku", "Gaming_Dexterity", "Gaming_Cerebral", "JP_PlaySugoroku", "JP_Sugoroku"),
new CommonTaxonomy.Rule("nelim.joypreservation", "JobGiver_DaMaJiang", "Joy_Chi_B", "Gaming_Cerebral", "Job_DaMaJiang", "SZ_MaJiangZhuo"),
new CommonTaxonomy.Rule("nelim.joypreservation", "ShareTribalLore", "Gaming_Cerebral", "Social", "ShareTribalLore", "TribalLoreFire"),
new CommonTaxonomy.Rule("nelim.joypreservation", "WatchPekingOpera", "Joy_Chi_A", "Television", "WatchPekingOpera", "Chi_JingJuZhanTai"),
new CommonTaxonomy.Rule("nelim.retrojoy", "PlayRimtendoES", "Gaming_Video", "JoyRescue_Kind_taxonomy_video", "PlayRimtendoES", "RimtendoESConsole"),
new CommonTaxonomy.Rule("nelim.tabletopdev", "UseRPGCampaign", "Gaming_RPG", "Gaming_Cerebral", "PlayRPGCampaign", "LongRPGCampaign", "MediumRPGCampaign", "ShortRPGCampaign"),
new CommonTaxonomy.Rule("nelim.wa", "Drink_GreenTea", "Enjoy_ChanoYu", "Gluttonous", "Drink_GreenTea", "WA_GreenTea"),
new CommonTaxonomy.Rule("nelim.wa", "Make_GreenTea", "Enjoy_ChanoYu", "Gluttonous", "Make_GreenTea", "WA_Chagama"),
new CommonTaxonomy.Rule("nelim.wa", "Play_BozuMekuri", "Enjoy_WA", "Gaming_Cerebral", "Play_BozuMekuri", "WA_Karuta"),
new CommonTaxonomy.Rule("nelim.wa", "Play_Koto", "Play_Music", "HighCulture", "Play_Koto", "WA_Koto"),
new CommonTaxonomy.Rule("nelim.wa", "Play_PoemCardGame", "Enjoy_WA", "Gaming_Cerebral", "Play_PoemCardGame", "WA_Karuta"),
new CommonTaxonomy.Rule("nelim.wa", "Play_ShellMatching", "Enjoy_WA", "Gaming_Cerebral", "Play_ShellMatching", "WA_ShellMatching"),
new CommonTaxonomy.Rule("nelim.wa", "Play_Sugoroku", "Gaming_Dexterity", "Gaming_Cerebral", "Play_Sugoroku", "WA_Sugoroku"),
new CommonTaxonomy.Rule("nelim.waamusementrenew", "JP_EnjoyAroma", "JP_EnjoyWa", "JoyRescue_Kind_taxonomy_wellbeing", "JP_EnjoyAroma", "JP_IncenseBurner"),
new CommonTaxonomy.Rule("nelim.waamusementrenew", "JP_PlayBozuMekuri", "JP_EnjoyWa", "Gaming_Cerebral", "JP_PlayBozuMekuri", "JP_Karuta"),
new CommonTaxonomy.Rule("nelim.waamusementrenew", "JP_PlayPoemCards", "JP_EnjoyWa", "Gaming_Cerebral", "JP_PlayPoemCards", "JP_Karuta"),
new CommonTaxonomy.Rule("nelim.waamusementrenew", "JP_PlayShellMatching", "JP_EnjoyWa", "Gaming_Cerebral", "JP_PlayShellMatching", "JP_ShellMatching"),
new CommonTaxonomy.Rule("nelim.waamusementrenew", "JP_PlaySugoroku", "Gaming_Dexterity", "Gaming_Cerebral", "JP_PlaySugoroku", "JP_Sugoroku"),
new CommonTaxonomy.Rule("nelim.zarstribalrebornrenew", "ShareTribalLore", "Gaming_Cerebral", "Social", "ShareTribalLore", "TribalLoreFire"),
new CommonTaxonomy.Rule("neronix17.clutterfurniture", "WatchHolograms", "Hologram", "Television", "WatchHologram", "HoloEkie", "HoloFlyingDots", "HoloSciSign"),
new CommonTaxonomy.Rule("ninedaylongbow.ChineseComprehensiveExpansion", "JobGiver_playmahjong", "Joy_mahjong", "Gaming_Cerebral", "Job_playmahjong", "HX_mahjong"),
new CommonTaxonomy.Rule("pipai.tabletopdev", "UseRPGCampaign", "Gaming_RPG", "Gaming_Cerebral", "PlayRPGCampaign", "LongRPGCampaign", "MediumRPGCampaign", "ShortRPGCampaign"),
new CommonTaxonomy.Rule("sand.sndlibrary", "SND_Study", "SND_Studying", "Reading", "SND_Study", "SNDLearningDesk"),
new CommonTaxonomy.Rule("sera.apinialienrace", "Apini_WatchLightshow", "Apini_Lightshow", "Television", "Apini_WatchLights", "Apini_PrismaticHoloimager"),
new CommonTaxonomy.Rule("ssulunge.KijinRace3", "BathHotSpringKijin", "Social", "JoyRescue_Kind_taxonomy_wellbeing", "BathHotSpringKijin", "HotSpringKijin"),
new CommonTaxonomy.Rule("tix.soundsystem", "HearingMusic", "Music", "HighCulture", "Music", "SoundSystem"),
new CommonTaxonomy.Rule("vanillaquestsexpanded.cryptoforge", "VQE_Play_WargamingTable", "VQE_Gaming_StrategicPlay", "Gaming_Cerebral", "VQE_Play_WargamingTable", "VQE_AncientWargamingTable"),
new CommonTaxonomy.Rule("wowgag.letsfishing", "LF_WatchAquarium", "LF_FishWatching", "Meditative", "LF_WatchAquarium", "LF_AquariumLarge", "LF_AquariumMedium", "LF_AquariumSmall"),
new CommonTaxonomy.Rule("zal.books", "LJO_ReadBook", "Meditative", "Reading", "LJO_ReadBook", "LJO_ReadingTable"),
new CommonTaxonomy.Rule("zal.earlytimes", "MedTimes_Use_BookReading", "ReadBook", "Reading", "ReadBook", "BookGraphicNovel"),
new CommonTaxonomy.Rule("zal.earlytimes", "MedTimes_Use_NoteReading", "ReadBook", "Reading", "ReadNote", "NoteGraphicNovel"),
new CommonTaxonomy.Rule("zal.earlytimes", "MedTimes_Use_PCJoyCombatGame", "Gaming_Dexterity", "JoyRescue_Kind_taxonomy_video", "MedTimes_PCJoyCombatGame", "MedTimes_PersonalComputer"),
new CommonTaxonomy.Rule("zal.earlytimes", "MedTimes_Use_PCJoyFPS", "Gaming_Dexterity", "JoyRescue_Kind_taxonomy_video", "MedTimes_PCJoyFPS", "MedTimes_PersonalComputer"),
new CommonTaxonomy.Rule("zal.earlytimes", "MedTimes_Use_PCJoyStrategy", "Gaming_Dexterity", "JoyRescue_Kind_taxonomy_video", "MedTimes_PCJoyStrategy", "MedTimes_PersonalComputer"),
new CommonTaxonomy.Rule("zal.earlytimes", "MedTimes_Use_PCJoySurfing", "Gaming_Cerebral", "Television", "MedTimes_PCJoySurfing", "MedTimes_PersonalComputer"),
new CommonTaxonomy.Rule("zal.earlytimes", "MedTimes_Use_Prayer_Creator", "WorshipGods", "Meditative", "MedTimes_Prayer_Creator", "MedTimes_Shrine_Creator"),
new CommonTaxonomy.Rule("zal.earlytimes", "MedTimes_Use_Prayer_Idol", "WorshipGods", "Meditative", "MedTimes_Prayer_Totem", "EarlyTimes_Shrine_Nature"),
new CommonTaxonomy.Rule("zal.earlytimes", "MedTimes_Use_Prayer_PangLi", "WorshipGods", "Meditative", "MedTimes_Prayer_PangLi", "MedTimes_Shrine_PangLi"),
new CommonTaxonomy.Rule("zal.earlytimes", "MedTimes_Use_Prayer_RNG", "WorshipGods", "Meditative", "MedTimes_Prayer_RNG", "MedTimes_Shrine_RandomNumberGod"),
new CommonTaxonomy.Rule("zal.earlytimes", "MedTimes_Use_SkillBookReading", "ReadBook", "Reading", "ReadSkillBook", "BookAnimals", "BookArtistic", "BookContruction", "BookCooking", "BookCrafting", "BookIntellectual", "BookMedicine", "BookMeleeCombat", "BookMining", "BookPlants", "BookRangedCombat", "BookSocial"),
new CommonTaxonomy.Rule("zal.earlytimes", "MedTimes_Use_SkillNoteReading", "ReadBook", "Reading", "ReadSkillNote", "NoteAnimals", "NoteArtistic", "NoteContruction", "NoteCooking", "NoteCrafting", "NoteIntellectual", "NoteMedicine", "NoteMeleeCombat", "NoteMining", "NotePlants", "NoteRangedCombat", "NoteSocial"),
new CommonTaxonomy.Rule("zal.juggling", "JuggleBalls", "Juggling", "Gaming_Dexterity", "Play_JuggleBalls", "JugglingBalls"),
new CommonTaxonomy.Rule("zal.jukebox", "JoyGiver_ListenSong", "JoyKind_ListenSong", "HighCulture", "JobDef_ListenSong", "JukeBox"),
new CommonTaxonomy.Rule("zal.leeani", "UseArchiveJoy", "Reading_Archive", "Reading", "UseArchiveJob", "LeeaniBookshelf"),
new CommonTaxonomy.Rule("zal.medievaltimes", "MedTimes_Use_DeskJoyDraw", "Gaming_Cerebral", "JoyRescue_Kind_taxonomy_creative", "MedTimes_DeskJoyDraw", "MedTimes_Desk"),
new CommonTaxonomy.Rule("zal.medievaltimes", "MedTimes_Use_DeskJoyMagazine", "Gaming_Cerebral", "Reading", "MedTimes_DeskJoyMagazine", "MedTimes_Desk", "MedTimes_SmallTable"),
new CommonTaxonomy.Rule("zal.medievaltimes", "MedTimes_Use_DeskJoyReading", "Gaming_Cerebral", "Reading", "MedTimes_DeskJoyReading", "MedTimes_Desk"),
new CommonTaxonomy.Rule("zal.medievaltimes", "MedTimes_Use_DeskJoyReadingShort", "Gaming_Cerebral", "Reading", "MedTimes_DeskJoyReadingShort", "MedTimes_Desk"),
new CommonTaxonomy.Rule("zal.medievaltimes", "MedTimes_Use_DeskJoyStory", "Gaming_Cerebral", "Reading", "MedTimes_DeskJoyStory", "MedTimes_Desk"),
new CommonTaxonomy.Rule("zal.medievaltimes", "MedTimes_Use_PCJoyCombatGame", "Gaming_Dexterity", "JoyRescue_Kind_taxonomy_video", "MedTimes_PCJoyCombatGame", "MedTimes_PersonalComputer"),
new CommonTaxonomy.Rule("zal.medievaltimes", "MedTimes_Use_PCJoyFPS", "Gaming_Dexterity", "JoyRescue_Kind_taxonomy_video", "MedTimes_PCJoyFPS", "MedTimes_PersonalComputer"),
new CommonTaxonomy.Rule("zal.medievaltimes", "MedTimes_Use_PCJoyModing", "Gaming_Cerebral", "JoyRescue_Kind_taxonomy_creative", "MedTimes_PCJoyModing", "MedTimes_PersonalComputer"),
new CommonTaxonomy.Rule("zal.medievaltimes", "MedTimes_Use_PCJoyStrategy", "Gaming_Dexterity", "JoyRescue_Kind_taxonomy_video", "MedTimes_PCJoyStrategy", "MedTimes_PersonalComputer"),
new CommonTaxonomy.Rule("zal.medievaltimes", "MedTimes_Use_PCJoySurfing", "Gaming_Cerebral", "Television", "MedTimes_PCJoySurfing", "MedTimes_PersonalComputer"),
new CommonTaxonomy.Rule("zal.radio", "ListenRadio", "Radio", "Television", "ListenRadio", "Radio"),
new CommonTaxonomy.Rule("zal.smallhotspring", "BathSmallHotSpring", "Meditative", "JoyRescue_Kind_taxonomy_wellbeing", "BathSmallHotSpring", "SmallHotSpring"),
new CommonTaxonomy.Rule("zal.tribalessentials", "ShareTribalLore", "Gaming_Cerebral", "Social", "ShareTribalLore", "TribalLoreFire"),
}; } }
